version: "3.5"

services:
  obp_institution_client:
    build: ./
    container_name: "obp_institution_client"
    restart: unless-stopped
    env_file:
      - ./var.env
    environment:
      - REACT_APP_API=http://172.21.0.4:8080
      - HOST=obp_institution_client
      - PORT=80
